---
- hosts: all
  pre_tasks:
    - name: ensure curl is installed
      package:
        name: curl
  roles:
    - vagrant
  vars:
    nginx_vhosts:
      - name: example
        listen: 80
        server_name: example.com
        root: /vagrant/public
