---
- name: ensure nginx is installed
  package:
    name: nginx

- include: vhosts/conf.yml
  when: ansible_os_family == 'RedHat'

- include: vhosts/sites.yml
  when: ansible_os_family == 'Debian'

- name: ensure nginx service runs
  service:
    name: nginx
    enabled: yes
    state: started

- name: ensure webserver ports are open in firewall
  firewalld:
    service: "{{ item[0] }}"
    zone: "{{ item[1] }}"
    permanent: true
    state: enabled
  with_nested:
    - [ "http", "https" ]
    - "{{ nginx_firewall_zones }}"
