---
- name: ensure nginx is installed
  package:
    name: nginx

- name: ensure directory for global nginx configuration files exists
  file:
    path: /etc/nginx/global.d
    state: directory

- name: ensure nginx vhosts are configured
  template:
    src: vhost.conf.j2
    dest: "/etc/nginx/conf.d/vhost_{{ item.name }}.conf"
    mode: 0644
  with_items: nginx_vhosts
  notify:
    - reload nginx

- name: ensure nginx service runs
  service:
    name: nginx
    enabled: yes
    state: started

- name: ensure webserver ports are open in firewall
  firewalld:
    service: "{{ item[0] }}"
    zone: "{{ item[1] }}"
    permanent: true
    state: enabled
  with_nested:
    - [ "http", "https" ]
    - "{{ nginx_firewall_zones }}"
