---
- name: ensure nginx vhosts are configured
  template:
    src: vhost.conf.j2
    dest: "/etc/nginx/conf.d/vhost_{{ item.name }}.conf"
    mode: 0644
  with_items: "{{ nginx_vhosts }}"
  notify:
    - reload nginx
